'use client';

import { useCallback, useState } from 'react';

interface UsePDFExportReturn {
  isExporting: boolean;
  exportPDF: (canvasElementId: string) => Promise<void>;
}

export function usePDFExport(): UsePDFExportReturn {
  const [isExporting, setIsExporting] = useState(false);

  const exportPDF = useCallback(async (canvasElementId: string) => {
    setIsExporting(true);
    try {
      const html2canvas = (await import('html2canvas')).default;
      const jsPDF = (await import('jspdf')).default;

      const element = document.getElementById(canvasElementId);
      if (!element) throw new Error(`Element #${canvasElementId} not found`);

      const canvasImage = await html2canvas(element, { scale: 2 });
      const imgData = canvasImage.toDataURL('image/png');

      const pdf = new jsPDF('landscape', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();

      // Header
      pdf.setFontSize(20);
      pdf.text('Trust Mapping Session', pageWidth / 2, 15, { align: 'center' });
      pdf.setFontSize(10);
      pdf.text(new Date().toLocaleDateString(), pageWidth / 2, 22, { align: 'center' });

      // Canvas image (fills page minus header/footer margins)
      const imgWidth = pageWidth - 20;
      const imgHeight = (canvasImage.height * imgWidth) / canvasImage.width;
      const maxImgHeight = pageHeight - 45;
      const finalHeight = Math.min(imgHeight, maxImgHeight);
      const finalWidth = (canvasImage.width * finalHeight) / canvasImage.height;

      pdf.addImage(imgData, 'PNG', (pageWidth - finalWidth) / 2, 28, finalWidth, finalHeight);

      // Footer
      pdf.setFontSize(8);
      pdf.text('Generated by True Valence Mapper', pageWidth / 2, pageHeight - 5, { align: 'center' });

      const dateStr = new Date().toISOString().split('T')[0];
      pdf.save(`trust-map-${dateStr}.pdf`);
    } catch (error) {
      console.error('PDF export failed:', error);
      // Fallback: browser print dialog
      window.print();
    } finally {
      setIsExporting(false);
    }
  }, []);

  return { isExporting, exportPDF };
}
