'use client';

import { useCallback, useState } from 'react';
import type { Relationship } from '../types';

interface UsePDFExportReturn {
  isExporting: boolean;
  exportPDF: (canvasElementId: string, relationships?: Relationship[]) => Promise<void>;
}

export function usePDFExport(): UsePDFExportReturn {
  const [isExporting, setIsExporting] = useState(false);

  const exportPDF = useCallback(async (canvasElementId: string, relationships?: Relationship[]) => {
    setIsExporting(true);
    try {
      const html2canvas = (await import('html2canvas')).default;
      const jsPDF = (await import('jspdf')).default;

      const element = document.getElementById(canvasElementId);
      if (!element) throw new Error(`Element #${canvasElementId} not found`);

      const canvasImage = await html2canvas(element, { scale: 2 });
      const imgData = canvasImage.toDataURL('image/png');

      const pdf = new jsPDF('landscape', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();

      // Header
      pdf.setFontSize(20);
      pdf.text('Trust Mapping Session', pageWidth / 2, 15, { align: 'center' });
      pdf.setFontSize(10);
      pdf.text(new Date().toLocaleDateString(), pageWidth / 2, 22, { align: 'center' });

      // Canvas image (fills page minus header/footer margins)
      const imgWidth = pageWidth - 20;
      const imgHeight = (canvasImage.height * imgWidth) / canvasImage.width;
      const maxImgHeight = pageHeight - 45;
      const finalHeight = Math.min(imgHeight, maxImgHeight);
      const finalWidth = (canvasImage.width * finalHeight) / canvasImage.height;

      pdf.addImage(imgData, 'PNG', (pageWidth - finalWidth) / 2, 28, finalWidth, finalHeight);

      // Footer
      pdf.setFontSize(8);
      pdf.text('Generated by True Valence Mapper', pageWidth / 2, pageHeight - 5, { align: 'center' });

      // Notes page — only when at least one relationship has a non-empty note
      const noteRels = (relationships ?? []).filter((r) => r.note?.trim());
      if (noteRels.length > 0) {
        pdf.addPage();
        pdf.setFontSize(14);
        pdf.text('Session Notes', 14, 18);
        pdf.setFontSize(10);
        let y = 30;
        for (const r of noteRels) {
          const lines = pdf.splitTextToSize(`${r.name} — ${r.note}`, pageWidth - 28);
          pdf.text(lines, 14, y);
          y += lines.length * 6 + 4;
          if (y > pageHeight - 20) { pdf.addPage(); y = 20; }
        }
      }

      const dateStr = new Date().toISOString().split('T')[0];
      pdf.save(`trust-map-${dateStr}.pdf`);
    } catch (error) {
      console.error('PDF export failed:', error);
      // Fallback: browser print dialog
      window.print();
    } finally {
      setIsExporting(false);
    }
  }, []);

  return { isExporting, exportPDF };
}
