'use client';

import { useState } from 'react';
import { SessionProvider, useSession } from '../context/SessionContext';
import { LandingScreen } from '../components/LandingScreen';
import { NamingScreen } from '../components/NamingScreen';
import { ScoringScreen } from '../components/ScoringScreen';
import { CanvasScreen } from '../components/CanvasScreen';
import { ExportSuccessScreen } from '../components/ExportSuccessScreen';
import { TrustDefinitionsModal } from '../components/TrustDefinitionsModal';

function AppContent() {
  const {
    relationships,
    trustLevels,
    currentStep,
    addRelationship,
    removeRelationship,
    updateRelationship,
    setTrustLevel,
    setCurrentStep,
    clearSession,
  } = useSession();

  const [showDefinitions, setShowDefinitions] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  async function handleExport() {
    setIsExporting(true);
    try {
      const html2canvas = (await import('html2canvas')).default;
      const jsPDF = (await import('jspdf')).default;

      const canvas = document.getElementById('trust-canvas');
      if (!canvas) throw new Error('Canvas not found');

      const canvasImage = await html2canvas(canvas, { scale: 2 });
      const imgData = canvasImage.toDataURL('image/png');

      const pdf = new jsPDF('landscape', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();

      // Header
      pdf.setFontSize(20);
      pdf.text('Trust Mapping Session', pageWidth / 2, 15, { align: 'center' });
      pdf.setFontSize(10);
      pdf.text(new Date().toLocaleDateString(), pageWidth / 2, 22, { align: 'center' });

      // Canvas image
      const imgWidth = pageWidth - 20;
      const imgHeight = (canvasImage.height * imgWidth) / canvasImage.width;
      const maxImgHeight = pageHeight - 45;
      const finalHeight = Math.min(imgHeight, maxImgHeight);
      const finalWidth = (canvasImage.width * finalHeight) / canvasImage.height;

      pdf.addImage(imgData, 'PNG', (pageWidth - finalWidth) / 2, 28, finalWidth, finalHeight);

      // Footer
      pdf.setFontSize(8);
      pdf.text('Generated by True Valence Mapper', pageWidth / 2, pageHeight - 5, { align: 'center' });

      const dateStr = new Date().toISOString().split('T')[0];
      pdf.save(`trust-map-${dateStr}.pdf`);

      setCurrentStep('complete');
    } catch (error) {
      console.error('PDF export failed:', error);
      // Fallback: browser print
      window.print();
    } finally {
      setIsExporting(false);
    }
  }

  function handleNewSession() {
    clearSession();
  }

  return (
    <main className="min-h-screen bg-white">
      {currentStep === 'landing' && (
        <LandingScreen
          onStartSession={() => setCurrentStep('naming')}
          onOpenDefinitions={() => setShowDefinitions(true)}
        />
      )}

      {currentStep === 'naming' && (
        <NamingScreen
          relationships={relationships}
          onAdd={addRelationship}
          onRemove={removeRelationship}
          onUpdate={updateRelationship}
          onNext={() => setCurrentStep('scoring')}
          onOpenDefinitions={() => setShowDefinitions(true)}
        />
      )}

      {currentStep === 'scoring' && (
        <ScoringScreen
          relationships={relationships}
          trustLevels={trustLevels}
          onSetTrustLevel={setTrustLevel}
          onNext={() => setCurrentStep('canvas')}
          onBack={() => setCurrentStep('naming')}
          onOpenDefinitions={() => setShowDefinitions(true)}
        />
      )}

      {currentStep === 'canvas' && (
        <>
          <CanvasScreen
            relationships={relationships}
            trustLevels={trustLevels}
            onExport={handleExport}
            onBack={() => setCurrentStep('scoring')}
          />
          {isExporting && (
            <div
              className="fixed inset-0 z-50 flex items-center justify-center bg-white/80"
              role="status"
              aria-label="Generating PDF..."
            >
              <div className="flex flex-col items-center gap-3 text-primary">
                <svg
                  className="h-10 w-10 animate-spin"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  aria-hidden="true"
                >
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                <span className="text-sm font-medium text-gray-dark">Generating PDF…</span>
              </div>
            </div>
          )}
        </>
      )}

      {currentStep === 'complete' && (
        <ExportSuccessScreen onNewSession={handleNewSession} />
      )}

      <TrustDefinitionsModal
        isOpen={showDefinitions}
        onClose={() => setShowDefinitions(false)}
      />
    </main>
  );
}

export default function Home() {
  return (
    <SessionProvider>
      <AppContent />
    </SessionProvider>
  );
}
